### ISSUE TITLE
bug: cast doesn’t work in android

### ISSUE THREAD

**Issue by riderx** [Cap-go/ivs-player#20]
In iOS when we click on cast it open the airplay menu, it should do the same for chromecast in android.

**Comment by PrabhbirJ** [comment]
@riderx Hi there! Just wanted to confirm what seems to be the problem is the cast menu not opening? or the menu is opening but the playback is not starting on the screen?

**Comment by riderx** [comment]
I found the solution myself it was a miss config of the cast receiver id.
Thanks a lot for the help

**Comment by rishi-raj-jain** [comment]
Can we close this off on Algora as well?
